name: Publish To Docker Hub

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_TAG: ${GITHUB_REF/refs\/tags\//}
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/sypex-geo:${{env.GIT_TAG}}
    - name: Publish the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/sypex-geo:${{env.GIT_TAG}}
